export const OWNER_LOGIN_REQUEST = 'OWNER_LOGIN_REQUEST';
export const OWNER_LOGIN_SUCCESS = 'OWNER_LOGIN_SUCCESS';
export const OWNER_LOGIN_FAIL = 'OWNER_LOGIN_FAIL';

export const OWNER_CREATE_REQUEST = 'OWNER_CREATE_REQUEST';
export const OWNER_CREATE_SUCCESS = 'OWNER_CREATE_SUCCESS';
export const OWNER_CREATE_FAIL = 'OWNER_CREATE_FAIL';

export const OWNER_LIST_REQUEST = 'OWNER_LIST_REQUEST';
export const OWNER_LIST_SUCCESS = 'OWNER_LIST_SUCCESS';
export const OWNER_LIST_FAIL = 'OWNER_LIST_FAIL';

export const OWNER_ADMIN_ROLE_UPDATE_REQUEST = 'OWNER_ADMIN_ROLE_UPDATE_REQUEST';
export const OWNER_ADMIN_ROLE_UPDATE_SUCCESS = 'OWNER_ADMIN_ROLE_UPDATE_SUCCESS';
export const OWNER_ADMIN_ROLE_UPDATE_FAIL = 'OWNER_ADMIN_ROLE_UPDATE_FAIL';

export const OWNER_DELETE_ADMIN_REQUEST = 'OWNER_DELETE_ADMIN_REQUEST';
export const OWNER_DELETE_ADMIN_SUCCESS = 'OWNER_DELETE_ADMIN_SUCCESS';
export const OWNER_DELETE_ADMIN_FAIL = 'OWNER_DELETE_ADMIN_FAIL';

export const OWNER_PASSWORD_RESET_REQUEST = 'OWNER_PASSWORD_RESET_REQUEST';
export const OWNER_PASSWORD_RESET_SUCCESS = 'OWNER_PASSWORD_RESET_SUCCESS';
export const OWNER_PASSWORD_RESET_FAIL = 'OWNER_PASSWORD_RESET_FAIL';

export const OWNER_PASSWORD_RESET_CONFIRM_REQUEST = 'OWNER_PASSWORD_RESET_CONFIRM_REQUEST';
export const OWNER_PASSWORD_RESET_CONFIRM_SUCCESS = 'OWNER_PASSWORD_RESET_CONFIRM_SUCCESS';
export const OWNER_PASSWORD_RESET_CONFIRM_FAIL = 'OWNER_PASSWORD_RESET_CONFIRM_FAIL';
